package moffy.ticex.registry;

import slimeknights.tconstruct.library.modifiers.Modifier;
import slimeknights.tconstruct.library.modifiers.util.DynamicModifier;
import slimeknights.tconstruct.library.modifiers.util.StaticModifier;

public class TicEXModifiers {
    public static DynamicModifier REBIRTH_MODIFIER = null;
    public static StaticModifier<Modifier> DEFLECTION_MODIFIER = null;
    public static StaticModifier<Modifier> EMBOSSMENT_MODIFIER = null;
    public static StaticModifier<Modifier> ENCHANTMENT_SUPPLIER_MODIFIER = null;
    public static StaticModifier<Modifier> OMNIPOTENCE_MODIFIER = null;
    public static DynamicModifier COSMIC_UNBREAKABLE_MODIFIER = null;
    public static DynamicModifier COSMIC_LUCK_MODIFIER = null;
    public static StaticModifier<Modifier> BEDROCK_BREAKER_MODIFIER = null;
    public static DynamicModifier TRANSCENDENTAL_MODIFIER = null;
    public static StaticModifier<Modifier> CELESTIAL_MODIFIER = null;
    public static DynamicModifier ETERNITY_MODIFIER = null;
    public static StaticModifier<Modifier> CONDENSING_MODIFIER = null;
    public static DynamicModifier DENSE_MODIFIER = null;
    public static StaticModifier<Modifier> AFTERSHOCK_MODIFIER = null;
    public static StaticModifier<Modifier> ENDESTSHOT_MODIFIER = null;
    public static DynamicModifier SKULLFIRE_MODIFIER = null;
    public static DynamicModifier BLAZING_FLAME_MODIFIER = null;
    public static DynamicModifier BLAZING_FORTUNE_MODIFIER = null;
    public static StaticModifier<Modifier> MEKANIC_MODIFIER = null;
    public static DynamicModifier RADIATION_SHIELDING_MODIFIER = null;
    public static StaticModifier<Modifier> SASSY_MODIFIER = null;
    public static StaticModifier<Modifier> DRAGON_FORCE_MODIFIER = null;
    public static StaticModifier<Modifier> EVOLVED_MODIFIER = null;
    public static DynamicModifier INJECT_MODIFIER = null;
    public static StaticModifier<Modifier> SOUL_RENDING_MODIFIER = null;
    public static StaticModifier<Modifier> KONPAKU_MODIFIER = null;
    public static StaticModifier<Modifier> KOSHIRAE_MODIFIER = null;
    public static StaticModifier<Modifier> PROUD_MODIFIER = null;
    public static StaticModifier<Modifier> APOTH_SUPPLIER_MODIFIER = null;
    public static StaticModifier<Modifier> OVERLOAD_MODIFIER = null;
    public static StaticModifier<Modifier> OVERRIDE_MODIFIER = null;
    public static StaticModifier<Modifier> INCOMPARABLE_MODIFIER = null;
    public static DynamicModifier CARDBOARD_MODIFIER = null;
    public static StaticModifier<Modifier> OVERCASTING_MODIFIER = null;
    public static StaticModifier<Modifier> CLUSTER_MODIFIER = null;
    public static StaticModifier<Modifier> ABYSSAL_MODIFIER = null;
    public static StaticModifier<Modifier> INFERNAL_MODIFIER = null;
    public static StaticModifier<Modifier> GRAVITY_MODIFIER = null;
    public static StaticModifier<Modifier> HURRICANE_MODIFIER = null;
    public static DynamicModifier MODEM_MODIFIER = null;
    public static StaticModifier<Modifier> PSIONIZING_RADIATION_MODIFIER = null;
    public static StaticModifier<Modifier> SOCKET_MODIFIER = null;
    public static StaticModifier<Modifier> SENSOR_MODIFIER = null;
    public static DynamicModifier AHRIM_MODIFIER = null;
    public static DynamicModifier DHAROK_MODIFIER = null;
    public static DynamicModifier GUTHAN_MODIFIER = null;
    public static DynamicModifier TORAG_MODIFIER = null;
    public static DynamicModifier VERAC_MODIFIER = null;
    public static DynamicModifier KARIL_MODIFIER = null;
    public static DynamicModifier NECTAR_MODIFIER = null;
    public static StaticModifier<Modifier> REACTIVE_MODIFIER = null;
    public static StaticModifier<Modifier> ALTERATIVE_MODIFIER = null;
    public static StaticModifier<Modifier> AFLOAT_MODIFIER = null;
    public static StaticModifier<Modifier> DUNGEON_MASTER_MODIFIER = null;
    public static StaticModifier<Modifier> UNRAVEL_MODIFIER = null;
    public static StaticModifier<Modifier> TELESCOPE_MODIFIER = null;
    public static StaticModifier<Modifier> PLANETARIUM_MODIFIER = null;
}
